Compile error fix with boost 1.36.0, gcc 4.2.3 on SLAMD64 12.1 reported as issue 260: cpdf.cc: In static member function ?static boost::shared_ptr<pdfobjects::CPdf> pdfobjects::CPdf::getInstance(const char*, pdfobjects::CPdf::OpenMode)?: cpdf.cc:2401: error: reference to ?exception? is ambiguous /usr/lib64/gcc/x86_64-slamd64-linux/4.2.3/../../../../include/c++/4.2.3/exception:57: error: candidates are: class std::exception /usr/include/boost-1_36/boost/exception/exception.hpp:47: error: class boost::exception
* all catch(exception&) changed to contain std namespace