tools: fix parse_object building
parse_object is missing its target for binary. This resulted in an implicit
rule being used and so the compilation failed because our CXXFLAGS are not
used (include path is missing etc..).

parse_object.cc also needs a minor compilation fix. g++ doesn't like
<::Type> construct:
parse_object.cc:109: error: '<::' cannot begin a template-argument list
parse_object.cc:109: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'