tools: pagemetrics 64b compilation fix
size_t is unsigned long on LP 64b systems and std::min doesn't have any
variant for unsigned long, unsigned int parameters.
Let's make from, to unsigned long to match CPdf::getPageCount return value.

Error message:
pagemetrics.cc:137: error: no matching function for call to ‘min(size_t&, unsigned int)’